### ISSUE TITLE
支持爱发电

### ISSUE THREAD

**Issue by ModyQyW** [ModyQyW/sponsors#2]

**Comment by ModyQyW** [comment]
@Megasu 感谢你在爱发电上的捐赠。 目前我正在试着增加 sponsorkit 对于爱发电的支持，后续才能展示你的基本信息，对此表示歉意。

**Comment by ModyQyW** [comment]
https://cdn.jsdelivr.net/gh/ModyQyW/sponsors/sponsorkit/sponsors.svg

应该能正常显示了

**Comment by Megasu** [comment]
🌹
